### ISSUE TITLE
GoogleMaps

### ISSUE THREAD

**Issue by TaeseongYun** [DDD-4/mayday-android#16]

**Comment by TaeseongYun** [comment]
[참고자료](https://webnautes.tistory.com/647)

**Comment by TaeseongYun** [comment]
@developer-sungjae 
구글맵 사용하려면 SHA-1 키 등록해야하는데 제것이 등록이 안되있어서 확인이 어려워요 ~
url 주시면 제가 추가하도록 할게요 ~

**Comment by developer-sungjae** [comment]
@TaeseongYun 
음.. 제 구글아이디로 했는데 태성님 SHA-1키를 제가 등록해야하는건가요?? 어떤 url을 드리면 되나요?

**Comment by TaeseongYun** [comment]
@developer-sungjae 
제가 이번에도 두루뭉실하게 전달드렸군요 ...
성재님 개인 구글아이디 비번을 받아 제가 등록하려 했는데 그러기엔 보안문제도 있고 그래서
이따 저녁쯤 sha-1키를 제가 드리면 어떨까 싶은데 괜찮으신가요 ?

**Comment by developer-sungjae** [comment]
@TaeseongYun 

제가 하는건 상관없는데 지금 이거 풀리퀘 진행중이라 제 단에서 태성님으로부터 받아서 한다면 어떻게 반영해야될까요?

**Comment by TaeseongYun** [comment]
@developer-sungjae 
sha 키를 제가 카톡으로 드릴게요 ~ API 키 설정하는 부분에 보시면 `패키지이름 및 지문추가`가 있어요

**Comment by TaeseongYun** [comment]
@developer-sungjae 
풀리퀘 진행 중 이라고 하셨는데 혹시 어떤거 작업 하고계신지 알 수 있을까요 ?
작업하고 있으시면 이슈에 어떤 UI 작업하고 있는지 이슈 등록 한번 부탁드리겠습니다 🙏🙏

**Comment by developer-sungjae** [comment]
@TaeseongYun 
그것이 아니라 지금 태성님이 진행중이신데 mayday계정에 등록해도 api key는 태성님이 직접 넣으셔야 되서 말씀드린겁니다
그래서 mayday 계정을 새로 만든건데 저한테 등록하라고 하셨는데 그럼 제가 등록해서 그걸 머지하는 쪽으로 하시는건가요?

**Comment by TaeseongYun** [comment]
@developer-sungjae 
성재님이 계정 알려주셨군요 못 받은줄 알았습니다.... 담부턴 유의하여 보도록 하겠습니다

sha 키는 제가 등록하도록 할게요.

**Comment by developer-sungjae** [comment]
# #9

**Comment by TaeseongYun** [comment]
### 해결완료.
