### ISSUE TITLE
UseCase  Result 패턴 도입 논의

### ISSUE THREAD

**Issue by TaeseongYun** [DDD-4/mayday-android#22]
@developer-sungjae 
PR 리뷰 중 usecase 를 사용하면 조금 더 괜찮을거 같다. 라는 의견이 나와서 그런데
usecase 와 result 패턴을 도입하는거에 대해 어떻게 생각하시나요 ?

- usecase (Functional Style)
[유즈케이스](https://medium.com/@june.pravin/clean-architecture-functional-style-use-case-composition-with-rxjava-kotlin-898726c97dfe) 

- 참조 코드
[Android-Clean-Architecture-MVVM-Dagger-RX](https://github.com/ZahraHeydari/Android-Clean-Architecture-MVVM-Dagger-RX/blob/5b5a37f8f98ab43e833ba18d158758285df88ab4/app/src/main/java/com/android/artgallery/presentation/detailphoto/PhotoDetailViewModel.kt)

**Comment by developer-sungjae** [comment]
전 좀 소화하기 버거울 것 같은데 도입한다고 하시면 따라가야죠ㅎ
