### ISSUE TITLE
 Gradle Groovy DSL->Gradle Kotlin DSL

### ISSUE THREAD

**Issue by TaeseongYun** [DDD-4/mayday-android#7]

**Comment by developer-sungjae** [comment]
@TaeseongYun  빌드 배포 도구인 Gradle의 Groovy 언어로 된것을 kotlin으로 바꾸는 것이므로 Gradle Groovy DSL -> Gradle Kotlin DSL 또는 Gradle Language 변경 Groovy -> Kotlin이 더 정확할 것 같습니다!

**Comment by TaeseongYun** [comment]
변경완료 .

**Comment by developer-sungjae** [comment]
@TaeseongYun 
https://kotlinlang.org/docs/reference/using-gradle.html
참고하시면 좋을 것 같아요

**Comment by TaeseongYun** [comment]
@developer-sungjae 

디폴트 모듈을 presenter로 변경하실 때 어떻게 핸들링 하셨나요 ?
마스터 브랜치 받아보니 presentation 모듈이 아예 잡히질 않네요

**Comment by TaeseongYun** [comment]
패키지 중복 등록으로인한 CI 통과 실패 이슈 발생.
## 해결완료
